<a href="<?php echo $block->getUrl('userproducts/*/index')?>" class="action primary">Go back</a>
<h1>Edit page</h1>


<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
     enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
    <input type="hidden" name="hid" id="hid" value="<?php echo $block->getId() ?>" />  
     
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>"  class="input-text" type="text" data-validate="{required:true}" value="<?php echo $block->getName('name') ?>"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="price"><span><?= $block->escapeHtml(__('Price')) ?></span></label>
            <div class="control">
                <input name="price" id="price" title="<?= $block->escapeHtmlAttr(__('Price')) ?>" class="input-text" type="text" data-validate="{required:true}" value="<?php echo $block->getPrice('price') ?>"/>
            </div>
        </div>
        <div class="field name ">
            <label class="label" for="image"><span><?= $block->escapeHtml(__('Image')) ?></span></label>
            <div class="control">
                <input name="image" type="file" id="image" title="<?= $block->escapeHtmlAttr(__('Image')) ?>" class="input-text" type="text" data-validate="{required:false}"/>
            </div>
        </div>   
    
        <div class="field image-preview">
            <label class="label" for="image-preview"><span><?= $block->escapeHtml(__('Image Preview')) ?></span></label>
            <div class="control">
                <img id="image-preview" src="/media/images/<?= $block->getImagePreview() ?>" alt="Image Preview" style="max-width: 200px;" />
            </div>
        </div>
        
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Save changes')) ?></span>
            </button>
        </div>
    </div>
</form>

<script>
var content =document.getElementById("hcontent").value; 
document.addEventListener("DOMContentLoaded", function(){
    document.getElementById("content").value = content;
});
</script>